### ISSUE TITLE
Section 2.2 cannot "select outgoing edges"

### ISSUE THREAD

**Issue by scottdangelo** [IBM/deploy-graph-db-container#1]
In section 2.2 are the following instructions:

```
Click on the User vertex at the center. In the ring that pops up, select outgoing edges, and click on rated.
```

I have hovered over and clicked all of the elements that show up in the ring, but I cannot get the rated movies to show up.
Perhaps the instructions need to be clarified or a screenshot should be added.

**Comment by shivahr** [comment]
Thanks Scott. I have added the missing snapshot. Hope you can get it working now.
