### ISSUE TITLE
Update product name

### ISSUE THREAD

**Issue by stevemar** [IBM/deploy-graph-db-container#18]
Hi @shivahr there are several instances of Bluemix in the README. Can you update it to say IBM Cloud?

Also, the `bx` tool is deprecated. Please update the instructions to use the `ibmcloud` CLI instead.

**Comment by Neha-Setia** [comment]
@stevemart  @maheshwarishikha  I have updated the readme :)

**Comment by stevemar** [comment]
Thanks!
