### ISSUE TITLE
Replication config

### ISSUE THREAD

**Issue by haseebnaseem** [IBM/deploy-graph-db-container#2]
The doc on scalability set the architecture for a OrientDb cluster but after proving that there isn't any replication, it didn't comment on how to configure the cluster for replication. Any ideas?

**Comment by shivahr** [comment]
Hi, the doc on Scalability is a work in progress. The next step is to configure Hazelcast for OrientDB database replication.
Happy to know your interest in this. I will inform back on this issue once the work on Scalability doc is complete.

**Comment by shivahr** [comment]
Hi,
We will publish the work on scalable deployment of OrientDB on Bluemix Kubernetes as a separate IBM developer journey (the current work in progress can be found at https://github.com/shivahr/Scalable-OrientDB-deployment-on-Kubernetes) and we will restrict the scope of this github repo to single pod deployment of OrientDB on Kubernetes (so as to keep the introduction of concepts and steps simple). Hence closing this. Kindly follow the above work-in-progress journey for updates.
