### ISSUE TITLE
Is it necessary to use  ` --validate=false` ?

### ISSUE THREAD

**Issue by scottdangelo** [IBM/deploy-graph-db-container#6]
The fix for Issue #3 had the following command to create the persistent volume:
```
$ kubectl apply -f local-volumes.yaml --validate=false
```
The README still has the following: 
```
$ kubectl apply -f local-volumes.yaml
```
I'm not sure if the `--validate=false` is ultimately necessary to fix the issue seen in #3 ?
If it is necessary, the README should be changed. If not, this bug can just be closed. Thanks.

**Comment by shivahr** [comment]
Hi Scott, the `--validate=false` argument is no more needed. (Since we are no more using the `type: DirectoryOrCreate`). Thanks for confirming.
